<html><head>
    <title>Map Tiles+Leaflet</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.js"></script>
    <script type="text/javascript" src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.js"></script>
    <link rel="stylesheet" type="text/css" href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.css">
    <script type="text/javascript" src="https://rawgit.com/mapbox/mapbox-gl-leaflet/master/leaflet-mapbox-gl.js"></script>

    <style type="text/css">
        html, body, #my-map {
            width: 100%;
            height: 100%;
            margin: 0;
        }
  </style>
</head>
<body>
    <div id="my-map"></div>
    <script type="text/javascript">
        // The Leaflet map Object
        var map = L.map('my-map').setView([{{$asset->location_latitude}}, {{$asset->location_longitude}}], 15);
        
        // the attribution is required for the Geoapify Free tariff plan
        map.attributionControl.setPrefix('').addAttribution('Powered by <a href="https://www.geoapify.com/" target="_blank">Geoapify</a> | © OpenStreetMap <a href="https://www.openstreetmap.org/copyright" target="_blank">contributors</a>');
    
        // Get your own API Key on https://myprojects.geoapify.com
        var myAPIKey = "f1c7105b6776456bbea07cea5cb97fbc"; 
    
        var gl = L.mapboxGL({
            style: `https://maps.geoapify.com/v1/styles/osm-bright/style.json?apiKey=${myAPIKey}`,
            accessToken: 'no-token'
        }).addTo(map);


        // Retina displays require different mat tiles quality
        const isRetina = L.Browser.retina;

        const baseUrl = "https://maps.geoapify.com/v1/tile/osm-bright/{z}/{x}/{y}.png?apiKey={apiKey}";
        const retinaUrl = "https://maps.geoapify.com/v1/tile/osm-bright/{z}/{x}/{y}@2x.png?apiKey={apiKey}";

        // Add map tiles layer. Set 20 as the maximal zoom and provide map data attribution.
        L.tileLayer(isRetina ? retinaUrl : baseUrl, {
        attribution: 'Powered by <a href="https://www.geoapify.com/" target="_blank">Geoapify</a> | © OpenStreetMap <a href="https://www.openstreetmap.org/copyright" target="_blank">contributors</a>',
        apiKey: myAPIKey,
        maxZoom: 20,
        id: 'osm-bright',
        }).addTo(map);

        //add a marker with icon generated by Geoapify Marker Icon API
        const markerIcon = L.icon({
        iconUrl: `https://api.geoapify.com/v1/icon?size=xx-large&type=awesome&color=%233e9cfe&icon=paw&apiKey=${myAPIKey}`,
        iconSize: [31, 46], // size of the icon
        iconAnchor: [15.5, 42], // point of the icon which will correspond to marker's location
        popupAnchor: [0, -45] // point from which the popup should open relative to the iconAnchor
        });

        const zooMarkerPopup = L.popup().setContent("{{$asset->certificate_number}}");
        const zooMarker = L.marker([{{$asset->location_latitude}}, {{$asset->location_longitude}}], {
        icon: markerIcon
        }).bindPopup(zooMarkerPopup).addTo(map);

    </script>
</body></html>